# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
  push:
    branches: ["main"]
    tags:
      - "v*.*.*"
      - "latest"
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      # - name: Verify formatting
      #   run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test -A
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Build for linux
        run: deno compile --target x86_64-unknown-linux-gnu --output dotenv-linux-x86 -RWE main.ts 
      - name: Upload linux artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: dotenv-linux-x86
          path: ./dotenv-linux-x86

      - name: Build for OSX (Intel)
        run: deno compile --target x86_64-apple-darwin --output dotenv-darwin-x86 -RWE main.ts 
      - name: Upload OSX Intel artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: dotenv-darwin-x86
          path: ./dotenv-darwin-x86

      - name: Build for OSX (Apple Silicon)
        run: deno compile --target aarch64-apple-darwin --output dotenv-darwin-aarch64 -RWE main.ts 
      - name: Upload OSX Apple Silicon artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: dotenv-darwin-aarch64
          path: ./dotenv-darwin-aarch64

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dotenv-darwin-aarch64
            dotenv-linux-x86
            dotenv-darwin-x86

